package price

// Code generated by scripts/updatePrice.py. DO NOT EDIT.
// Last updated: 2026-05-11 00:00:00 UTC

import (
	"sync"

	"github.com/bestruirui/octopus/internal/model"
)

var llmPriceLock sync.RWMutex

var llmPrice = map[string]model.LLMPrice{
	"gpt-5.5":                    {Input: 5, Output: 30, CacheRead: 0.5, CacheWrite: 0},
	"gpt-5.5-2026-04-23":         {Input: 5, Output: 30, CacheRead: 0.5, CacheWrite: 0},
	"gpt-5.5-pro":                {Input: 30, Output: 180, CacheRead: 0, CacheWrite: 0},
	"gpt-5.5-pro-2026-04-23":     {Input: 30, Output: 180, CacheRead: 0, CacheWrite: 0},
	"gpt-5.4":                    {Input: 2.5, Output: 15, CacheRead: 0.25, CacheWrite: 0},
	"gpt-5.4-2026-03-05":         {Input: 2.5, Output: 15, CacheRead: 0.25, CacheWrite: 0},
	"gpt-5.4-mini":               {Input: 0.75, Output: 4.5, CacheRead: 0.075, CacheWrite: 0},
	"gpt-5.4-mini-2026-03-17":    {Input: 0.75, Output: 4.5, CacheRead: 0.075, CacheWrite: 0},
	"gpt-5.4-nano":               {Input: 0.2, Output: 1.25, CacheRead: 0.02, CacheWrite: 0},
	"gpt-5.4-nano-2026-03-17":    {Input: 0.2, Output: 1.25, CacheRead: 0.02, CacheWrite: 0},
	"claude-opus-4-7":            {Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
	"claude-opus-4-6":            {Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
	"claude-opus-4-5":            {Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
	"claude-opus-4-5-20251101":   {Input: 5, Output: 25, CacheRead: 0.5, CacheWrite: 6.25},
	"claude-sonnet-4-6":          {Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 3.75},
	"claude-sonnet-4-5":          {Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 3.75},
	"claude-sonnet-4-5-20250929": {Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 3.75},
	"claude-haiku-4-5":           {Input: 1, Output: 5, CacheRead: 0.1, CacheWrite: 1.25},
	"claude-haiku-4-5-20251001":  {Input: 1, Output: 5, CacheRead: 0.1, CacheWrite: 1.25},
	"gemini-3-pro-preview":       {Input: 2, Output: 12, CacheRead: 0.2, CacheWrite: 0},
	"gemini-3-flash-preview":     {Input: 0.5, Output: 3, CacheRead: 0.05, CacheWrite: 0},
	"deepseek-v4-flash":          {Input: 0.14, Output: 0.28, CacheRead: 0.0028, CacheWrite: 0},
	"deepseek-v4-pro":            {Input: 1.74, Output: 3.48, CacheRead: 0.0145, CacheWrite: 0},
	"grok-4.3":                   {Input: 1.25, Output: 2.5, CacheRead: 0, CacheWrite: 0},
	"qwen3.6-max-preview":        {Input: 9, Output: 54, CacheRead: 0, CacheWrite: 0},
	"qwen3.6-plus":               {Input: 2, Output: 12, CacheRead: 0, CacheWrite: 0},
	"qwen3.6-plus-2026-04-02":    {Input: 2, Output: 12, CacheRead: 0, CacheWrite: 0},
	"qwen3.6-flash":              {Input: 1.2, Output: 7.2, CacheRead: 0, CacheWrite: 0},
	"qwen3.6-flash-2026-04-16":   {Input: 1.2, Output: 7.2, CacheRead: 0, CacheWrite: 0},
	"qwen3.6-35b-a3b":            {Input: 1.8, Output: 10.8, CacheRead: 0, CacheWrite: 0},
	"qwen3.6-27b":                {Input: 3, Output: 18, CacheRead: 0, CacheWrite: 0},
	"qwen3-max":                  {Input: 2.5, Output: 10, CacheRead: 0, CacheWrite: 0},
	"qwen3-max-2026-01-23":       {Input: 2.5, Output: 10, CacheRead: 0, CacheWrite: 0},
	"glm-5.1":                    {Input: 6, Output: 24, CacheRead: 1.3, CacheWrite: 0},
	"glm-5":                      {Input: 4, Output: 18, CacheRead: 0, CacheWrite: 0},
	"glm-5-turbo":                {Input: 5, Output: 22, CacheRead: 0, CacheWrite: 0},
	"glm-4.7":                    {Input: 2, Output: 8, CacheRead: 0, CacheWrite: 0},
	"glm-4.7-flash":              {Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	"glm-4.7-flashx":             {Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
	"glm-4.6":                    {Input: 0.6, Output: 2.2, CacheRead: 0.11, CacheWrite: 0},
	"minimax-m2.7":               {Input: 0.3, Output: 1.2, CacheRead: 0.06, CacheWrite: 0.375},
	"minimax-m2.7-highspeed":     {Input: 0.6, Output: 2.4, CacheRead: 0.06, CacheWrite: 0.375},
	"minimax-m2.5":               {Input: 0.3, Output: 1.2, CacheRead: 0.03, CacheWrite: 0.375},
	"minimax-m2.5-highspeed":     {Input: 0.6, Output: 2.4, CacheRead: 0.03, CacheWrite: 0.375},
	"m2-her":                     {Input: 0.3, Output: 1.2, CacheRead: 0, CacheWrite: 0},
	"kimi-k2.6":                  {Input: 0.95, Output: 4, CacheRead: 0.16, CacheWrite: 0},
	"kimi-k2.5":                  {Input: 0.6, Output: 3, CacheRead: 0.1, CacheWrite: 0},
	"v0-1.5-md":                  {Input: 3, Output: 15, CacheRead: 0, CacheWrite: 0},
	"v0-1.5-lg":                  {Input: 15, Output: 75, CacheRead: 0, CacheWrite: 0},
	"v0-1.0-md":                  {Input: 3, Output: 15, CacheRead: 0, CacheWrite: 0},
}
