FROM debian:bookworm

ARG TARGETPLATFORM
ENV TZ=Asia/Shanghai

RUN apt-get update && apt-get install -y ca-certificates tzdata gosu && \
    ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata && \
    rm -rf /var/cache/apt/*  && \
    mkdir -p /app

COPY build/docker/${TARGETPLATFORM}/uni-router /app/uni-router
COPY scripts/dockerfiles/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]
